# scriptcast built-in theme: light
: SC set terminal-theme light
: SC set theme-frame true
: SC set theme-frame-bar true
: SC set theme-frame-bar-title Terminal
: SC set theme-frame-bar-color e8ecf8
: SC set theme-frame-bar-buttons true
: SC set theme-scriptcast-watermark true
: SC set theme-background f0f4ff,e2e8f8
: SC set theme-border-color 00000020
: SC set theme-border-width 1
: SC set theme-margin 32 32 64
: SC set theme-padding 14
: SC set theme-radius 12
: SC set theme-shadow true
: SC set theme-shadow-color 00000030
: SC set theme-shadow-radius 20
: SC set theme-shadow-offset-y 21
: SC set theme-shadow-offset-x 0
